version: '3.1'
services:
  db:
    image: postgres
    container_name: springboot_postgres_container
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_api:/var/lib/mysql
volumes:
  postgres_data_api:
